### ISSUE TITLE
"mixed declarations deprecations" not shown in sassmeister

### ISSUE THREAD

**Issue by raffi-46** [sass/sass-site#1194]
Last week (v1.78.0) it worked fine now when i add props below nesting it not shown error in console what just happened in new release (v1.79.2)

![image](https://github.com/user-attachments/assets/f8dc0c45-e4ae-4869-a188-dcc93929ca11)

**Comment by nex3** [comment]
In 1.79.0, we added a feature to limit the number of cases where this deprecation warning showed up to those where the interleaved declaration could plausibly change the styling of a page under the new ordering. In this case, the styles in `a h2` have a higher specificity than those in `a`, and so they'll always cascade based on specificity rather than document order, so it's safe—there's no need to prepare for the new ordering.
