### ISSUE TITLE
Sass Black Lives Matter Banner

### ISSUE THREAD

**Issue by golavr** [sass/sass-site#461]
Sass should not be a platform for political agendas.
Saas is part of open source community which is non political by its nature.
We share ideas, help each other w/o asking people what their political standpoint.
The content is irrelevant and i'm not going to address it.

Please remove the banner.
The world is facing many challenges over the recent months, starting a war over open source platforms won't help no one.

![image](https://user-images.githubusercontent.com/22896741/88370578-f22e4e00-cd9a-11ea-8607-745457494755.png)

**Comment by nex3** [comment]
Technical work is inseparable from politics, whether that's by causing or preventing harm to people, embedding biases in our products or working to highlight those biases so we move past them, pointedly avoiding any statement that could be too political or standing up for the rights of our fellow human beings. Even you are engaging in political action by demanding our silence on the subject of Black lives.

Sass in particular has always been a political project. From its earliest days it sought to empower designers, who tended to have a much stronger representation of marginalized groups than their engineering counterparts, and in so doing it gave these marginalized people a larger place and a louder voice in tech as a whole. The most prominent voices in the Sass community have always been people of color, queer people, and women, and empowering those people is a political act in an industry dominated by straight white men.

Saying "Black Lives Matter" isn't an abstract political point. It's a matter of life and death, particularly for our many Black users and contributors. Police violence is a part of their lives as Sass is a part of their lives, and we take a stand against that violence because we care about them as not just users but as whole people.
