### ISSUE TITLE
Overflow of text on mobile handsets in sass docs.

### ISSUE THREAD

**Issue by hugekontrast** [sass/sass-site#576]
Android version - 11
Chrome version - 92.0.4515.115
Docs section - At rules > at-for

![Screenshot_20210906-130240_Chrome](https://user-images.githubusercontent.com/44055846/132177789-097d4001-51de-46c1-b2d4-7201cf6672dd.jpg)

**Comment by Awjin** [comment]
Thanks for the catch. @jina could you take a look when you have a chance?

**Comment by jina** [comment]
Yeah, I am hoping to this weekend.

**Comment by jina** [comment]
I didn't get to finish this — will wrap up soon!

**Comment by kauefr** [comment]
This bug is the product of three factors:

1. Larger font-size in introduction
2. Length of this specific code snippet
3. The design decision in #281

1 and 2 could be mitigated by relocating the syntax example from the introduction, like in [at-rules/function](https://sass-lang.com/documentation/at-rules/function). I don't see a way to rewrite the snippet and meaningfully shorten it while keeping a good legibility (e.g. isn't something like `@for $var from <e1> to <e2> { ... }` too terse?).

For the 3rd point, we would have to either revert that change, or manually insert breaks in problematic snippets. Lemme know if y'all want some help and I'll open a PR.
