### ISSUE TITLE
Playground improvements (click-to-copy, default initial code, movable panels, etc.)

### ISSUE THREAD

**Issue by jgerigmeyer** [sass/sass-site#779]
Opening this issue to capture a number of proposed improvements to the new Sass Playground. Feel free to split this into separate issues as you see fit.

1. Default code contents on initial Playground load (if not following a direct link with existing contents)
2. Click-to-copy input SCSS/Sass or output CSS: see [design proposal](https://xd.adobe.com/view/84c872fe-0e51-46e4-a59c-f72aab2b8c6a-d19b/screen/413c2a93-be31-4b54-8bbe-ef30b8af2dd0/)
3. Link directly from code examples throughout to the site, to open the code in the Playground: see [design proposal](https://xd.adobe.com/view/84c872fe-0e51-46e4-a59c-f72aab2b8c6a-d19b/)
4. Drag to expand/collapse input/output/console panel widths: see [design proposal](https://xd.adobe.com/view/84c872fe-0e51-46e4-a59c-f72aab2b8c6a-d19b/screen/413c2a93-be31-4b54-8bbe-ef30b8af2dd0/)
5. Autocomplete Sass-specific keywords (e.g. `@use`, `@debug`) and in-scope variables
6. Click on line number in the Console to go to that line in the input panel
7. ~~Convert existing input between SCSS and Sass when switching between panels~~

**Comment by nex3** [comment]
I'm striking through number 7 as "infeasible". We actually used to maintain a tool that could do this, but it turns out that the ongoing maintenance cost of needing to be able to produce nicely-formatted source code for every type of source AST node is substantial. I don't think it's worth the value of using it in the playground.

**Comment by ravindUwU** [comment]
Thoughts on encoding the line number into the URL state and placing the cursor at that line when the playground loads? 🤔

**Comment by nex3** [comment]
That's an interesting idea. I wonder if it would make more sense to copy the location specifically when there's _highlighted_ text—it seems like the most likely use case is to indicate "look at this part of the code", and highlighting might be a clearer signal that the user intends the position to be meaningful.

**Comment by ravindUwU** [comment]
Oh that's way better!! I'd love to have a go at implementing this over the weekend 😄. I guess there are a few decisions to be made about 🤔,

1. The current URL state is `<inputFormat><outputFormat><content>` and doesn't include a content delimiter so I'm unsure if extending this format to include a selection is ideal... thoughts on making it a JSON object instead? Decoding can support both formats so that existing playground links won't break.
  
   ```typescript
   interface PlaygroundUrlState {
       inputFormat: Syntax;
       outputFormat: OutputStyle;
       selection?: [/* from: */ number, /* to: */ number];
   }
   ```
   
   a. Rename `inputFormat` to `isScss` or `scss`?
   b. Rename `outputFormat` to `isExpanded` or `expanded`?
   c. For both of the above, `0 | 1` for brevity or `boolean`?

2. Should highlights be more visually distinctive? Maybe `#EFEB88`?
   ![](https://github.com/sass/sass-site/assets/7352580/0c12a53a-5dda-4d54-91c7-f1f6627d6bfc)

3. Move this discussion to a separate, feature-specific issue?

**Comment by jgerigmeyer** [comment]
@nex3 I think this issue can now be close?
